name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - '28.2'
          - '29.4'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    
    - name: Install ast-grep
      run: |
        curl -L https://github.com/ast-grep/ast-grep/releases/latest/download/ast-grep-x86_64-unknown-linux-gnu.zip -o ast-grep.zip
        unzip ast-grep.zip
        sudo mv ast-grep /usr/local/bin/
        ast-grep --version
    
    - name: Run tests
      run: |
        emacs -batch -L . -l ast-grep.el -l tests/ast-grep-test.el -f ert-run-tests-batch-and-exit
