name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - "28.2"
          - "29.4"
          - "30.1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Install ast-grep
        run: |
          nix profile install nixpkgs#ast-grep
          ast-grep --version

      - name: Run tests
        run: |
          emacs -batch -L . -l ast-grep.el -l tests/ast-grep-test.el -f ert-run-tests-batch-and-exit
